//==============================================================
// Tiraggo custom "Query" class generated by My2ndGeneration
//==============================================================

using System;

using Tiraggo.Core;
using Tiraggo.Interfaces;
using Tiraggo.DynamicQuery;

namespace BusinessObjects
{
	public partial class EmployeesQuery : tgEmployeesQuery
	{
		public EmployeesQuery()
		{

		}
	}
}	
