//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.TiraggoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tgCollectionWCFPacketOfEmployeesCollection6xVTLYDI", Namespace="http://schemas.datacontract.org/2004/07/Tiraggo.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket))]
    public partial class tgCollectionWCFPacketOfEmployeesCollection6xVTLYDI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfService.TiraggoService.EmployeesCollection CollectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfService.TiraggoService.EmployeesCollection Collection {
            get {
                return this.CollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionField, value) != true)) {
                    this.CollectionField = value;
                    this.RaisePropertyChanged("Collection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EmployeesCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Employees")]
    [System.SerializableAttribute()]
    public class EmployeesCollection : System.Collections.Generic.List<BusinessObjects.Employees> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tgEntity", Namespace="http://schemas.datacontract.org/2004/07/Tiraggo.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.tgEmployees))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.Employees))]
    public partial class tgEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ModifiedColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfService.TiraggoService.tgDataRowState RowStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] ModifiedColumns {
            get {
                return this.ModifiedColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedColumnsField, value) != true)) {
                    this.ModifiedColumnsField = value;
                    this.RaisePropertyChanged("ModifiedColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WcfService.TiraggoService.tgDataRowState RowState {
            get {
                return this.RowStateField;
            }
            set {
                if ((this.RowStateField.Equals(value) != true)) {
                    this.RowStateField = value;
                    this.RaisePropertyChanged("RowState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="tgDataRowState", Namespace="www.tiraggo.com")]
    public enum tgDataRowState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 16,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TiraggoService.ITiraggoXmlClass")]
    public interface ITiraggoXmlClass {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiraggoXmlClass/Employees_LoadAll", ReplyAction="http://tempuri.org/ITiraggoXmlClass/Employees_LoadAllResponse")]
        BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiraggoXmlClass/Employees_QueryForCollection", ReplyAction="http://tempuri.org/ITiraggoXmlClass/Employees_QueryForCollectionResponse")]
        BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiraggoXmlClass/Employees_QueryForEntity", ReplyAction="http://tempuri.org/ITiraggoXmlClass/Employees_QueryForEntityResponse")]
        BusinessObjects.Employees Employees_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiraggoXmlClass/Employees_GetByPrimaryKey", ReplyAction="http://tempuri.org/ITiraggoXmlClass/Employees_GetByPrimaryKeyResponse")]
        BusinessObjects.Employees Employees_GetByPrimaryKey(int employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiraggoXmlClass/Employees_SaveCollection", ReplyAction="http://tempuri.org/ITiraggoXmlClass/Employees_SaveCollectionResponse")]
        BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_SaveCollection(BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiraggoXmlClass/Employees_SaveEntity", ReplyAction="http://tempuri.org/ITiraggoXmlClass/Employees_SaveEntityResponse")]
        BusinessObjects.Employees Employees_SaveEntity(BusinessObjects.Employees entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITiraggoXmlClassChannel : WcfService.TiraggoService.ITiraggoXmlClass, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiraggoXmlClassClient : System.ServiceModel.ClientBase<WcfService.TiraggoService.ITiraggoXmlClass>, WcfService.TiraggoService.ITiraggoXmlClass {
        
        public TiraggoXmlClassClient() {
        }
        
        public TiraggoXmlClassClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiraggoXmlClassClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiraggoXmlClassClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiraggoXmlClassClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_LoadAll() {
            return base.Channel.Employees_LoadAll();
        }
        
        public BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_QueryForCollection(string serializedQuery) {
            return base.Channel.Employees_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.Employees Employees_QueryForEntity(string serializedQuery) {
            return base.Channel.Employees_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.Employees Employees_GetByPrimaryKey(int employeeID) {
            return base.Channel.Employees_GetByPrimaryKey(employeeID);
        }
        
        public BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_SaveCollection(BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket collection) {
            return base.Channel.Employees_SaveCollection(collection);
        }
        
        public BusinessObjects.Employees Employees_SaveEntity(BusinessObjects.Employees entity) {
            return base.Channel.Employees_SaveEntity(entity);
        }
    }
}
