//===============================================================================
//                    Generated by http://www.My2ndGeneration.com
//===============================================================================

using System;

using Tiraggo.Core;
using Tiraggo.Interfaces;
using Tiraggo.DynamicQuery;

namespace BusinessObjects
{
	public partial class EmployeesQuery : tgEmployeesQuery
	{
		public EmployeesQuery()
		{

		}
	}
}	
